# Generated by Django 5.1.1 on 2024-09-16 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', unique=True)),
            ],
        ),
    ]
