# Generated by Django 5.1.1 on 2024-09-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
