# Generated by Django 5.1.1 on 2024-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_token_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('isSingle', models.BooleanField()),
                ('participants', models.CharField(default='80045d942e', max_length=1099511627776)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.TimeField(auto_now=True)),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_chats',
            field=models.CharField(default='80045d942e', max_length=1099511627776),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_list',
            field=models.CharField(default='80045d942e', max_length=1099511627776),
        ),
    ]
