# Generated by Django 5.1.1 on 2024-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_chats_participants_alter_user_active_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chatname',
            field=models.CharField(default='my chat', max_length=20),
        ),
    ]
