# Generated by Django 5.1.1 on 2024-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_chats_chatname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatid',
            field=models.IntegerField(default=-1),
        ),
    ]
