# Generated by Django 5.1.1 on 2024-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_message_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
