# Generated by Django 5.1.1 on 2024-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
